apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: taskapp.fantoforever.com
spec:
  api:
    loadBalancer:
      class: Network
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://taskapp-kops-state-fantoforever-com/taskapp.fantoforever.com
  sshKeyName: taskapp
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1a
      name: a
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1a
      name: a
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "cloudwatch:PutMetricData",
            "ec2:DescribeTags",
            "logs:PutLogEvents",
            "logs:DescribeLogStreams",
            "logs:DescribeLogGroups",
            "logs:CreateLogStream",
            "logs:CreateLogGroup"
          ],
          "Resource": "*"
        }
      ]
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.35.3
  networkCIDR: 10.0.0.0/16
  networkID: vpc-0695255ee4dd684f5
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 10.0.48.0/20
    id: subnet-074262f6803e6d54c
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.0.64.0/20
    id: subnet-03c1d537b40aafa48
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.0.0.0/20
    id: subnet-04145513e08adfbf4
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 10.0.16.0/20
    id: subnet-090e30bf154ce1798
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  topology:
    dns:
      type: None

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: taskapp.fantoforever.com
  name: control-plane-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20260218
  machineType: t3.small
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: taskapp.fantoforever.com
  name: nodes-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20260218
  machineType: t3.small
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: taskapp.fantoforever.com
  name: nodes-us-east-1b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20260218
  machineType: t3.small
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-east-1b
