#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

# --- CONFIGURE THESE VARIABLES ---
# Read the credentials from your terraform state natively
export AWS_ACCESS_KEY_ID=$(cd "$SCRIPT_DIR/../terraform" && terraform output -raw kops_iam_user_access_key_id)
export AWS_SECRET_ACCESS_KEY=$(cd "$SCRIPT_DIR/../terraform" && terraform output -raw kops_iam_user_secret_access_key)
export AWS_REGION="us-east-1"

# NOTE: Replace "example.com" with exactly the domain you put in your terraform.tfvars
DOMAIN_NAME="fantoforever.com" 

if [ "$DOMAIN_NAME" == "example.com" ]; then
  echo "❌ ERROR: You MUST change DOMAIN_NAME in scripts/deploy_kops.sh before running it!"
  exit 1
fi

CLUSTER_NAME="taskapp.${DOMAIN_NAME}"
KOPS_STATE_STORE="s3://taskapp-kops-state-${DOMAIN_NAME//./-}"

# Subnets and VPC exactly as generated by your Terraform
VPC_ID="vpc-09044840caf6cb906"
PRIVATE_SUBNETS="subnet-02f9523dac700e646,subnet-04b6ea88ea87882a7,subnet-0ab7b9cfa832f7522"
PUBLIC_SUBNETS="subnet-00678ede0deeb7dc1,subnet-091c6fe9433729cf3,subnet-00b7c0418305aaec8"
ZONES="us-east-1a,us-east-1b,us-east-1c"

echo "Creating Kops state store bucket if it doesn't exist..."
aws s3api create-bucket --bucket taskapp-kops-state-${DOMAIN_NAME//./-} --region us-east-1 || true
aws s3api put-bucket-versioning --bucket taskapp-kops-state-${DOMAIN_NAME//./-} --versioning-configuration Status=Enabled || true

echo "Generating Kops cluster configuration..."
mkdir -p "$SCRIPT_DIR/../kops"
kops create cluster \
  --name=${CLUSTER_NAME} \
  --state=${KOPS_STATE_STORE} \
  --cloud=aws \
  --network-id=${VPC_ID} \
  --subnets=${PRIVATE_SUBNETS} \
  --utility-subnets=${PUBLIC_SUBNETS} \
  --topology=private \
  --networking=calico \
  --control-plane-zones=${ZONES} \
  --zones=${ZONES} \
  --node-count=3 \
  --node-size=t3.medium \
  --control-plane-count=3 \
  --control-plane-size=t3.medium \
  --api-loadbalancer-type=public \
  --dry-run -o yaml > "$SCRIPT_DIR/../kops/cluster.yaml"

echo "---------------------------------------------------------"
echo "✅ Kops YAML definition generated at ../kops/cluster.yaml"
echo "To provision the cluster, run the following commands:"
echo ""
echo "export KOPS_STATE_STORE=${KOPS_STATE_STORE}"
echo "kops update cluster --name ${CLUSTER_NAME} --yes --admin"
echo "kops validate cluster --wait 10m"
